# Generated by Django 4.2 on 2023-04-10 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraPositions',
            new_name='CameraPosition',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Plates',
            new_name='Plate',
        ),
        migrations.RenameModel(
            old_name='Streams',
            new_name='Stream',
        ),
        migrations.RenameModel(
            old_name='ViolationTypes',
            new_name='ViolationType',
        ),
    ]
