# Generated by Django 4.2 on 2023-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_eventstatus_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
