# Generated by Django 4.2 on 2023-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_eventstatus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='image_path',
            field=models.FilePathField(blank=True, null=True, path='/home/red/Repos/IVMSDataset/12Apr2023NewLenswithFilterTest/110408frames'),
        ),
    ]
