# Generated by Django 4.2 on 2023-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_plate_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
