# Generated by Django 4.2 on 2024-04-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0007_alter_plate_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recording_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
